version: "3.7"
services:
  db:
    image: "postgres:15"
    container_name: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "meet"
  pgAdmin:
    image: "dpage/pgadmin4"
    container_name: "meet-pgadmin"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "password123"
    ports:
      - "5050:80"
    depends_on:
      - db
    links:
      - db:db
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ${PWD}/servers.json:/pgadmin4/servers.json
      - ${PWD}/pgpass:/pgpass
volumes:
  pgadmin-data: