version: "3.7"
services:
  db:
    image: "postgres:15"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_MULTIPLE_DATABASES: "meet_users, meet_tmp"
    volumes:
      - ${PWD}/sql/db-users.sql:/docker-entrypoint-initdb.d/db-init-users.sql
  pg-admin:
    image: "dpage/pgadmin4:8"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "password123"
    ports:
      - "5050:80"
    depends_on:
      - db
    links:
      - db:db
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ${PWD}/servers.json:/pgadmin4/servers.json
      - ${PWD}/pgpass:/pgpass
  fake-smtp-server:
    image: gessnerfl/fake-smtp-server:2.2.0
    hostname: "fake-smtp-server"
    restart: always
    environment:
      - FAKESMTP_AUTHENTICATION_USERNAME=myuser
      - FAKESMTP_AUTHENTICATION_PASSWORD=mysecretpassword
    ports:
      - "9025:8025"      #expose smtp port
      - "9080:8080"      #expose web ui
      - "9081:8081"
volumes:
  pgadmin-data: