postgres:
  url: "postgres://meet_users:meet_users@localhost:5432/meet_users?sslmode=disable"
smtp:
  host: "localhost"
  port: 9025
  from: "sender@meet.com"
  user: "myuser"
  password: "mysecretpassword"
templates:
  confirm-template: "<!DOCTYPE html>
<html>
<body>
    <h3>Name:</h3><span>{{.Name}}</span><br/><br/>
    <h3>Email:</h3><span>{{.Message}}</span><br/>
</body>
</html>"
